-- =============================================================================
-- DevForge — Database Schema
-- -----------------------------------------------------------------------------
-- Database : devforge
-- Engine   : PostgreSQL 13+
-- Usage    : psql -U postgres -f devforge.sql
--            (run from WSL; run this file against the default/admin database.
--             It creates the devforge database if missing, then all tables.)
-- Tables   : users, requirements, applications, requirement_applications
-- =============================================================================

-- PostgreSQL cannot run CREATE DATABASE inside a block or with IF NOT EXISTS,
-- so we generate the statement only when the database is missing, via \gexec.
SELECT 'CREATE DATABASE devforge'
WHERE NOT EXISTS (SELECT FROM pg_database WHERE datname = 'devforge')\gexec

\connect devforge

-- -----------------------------------------------------------------------------
-- users  — accounts for everyone, including developers/owners
-- -----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS users (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username      TEXT        NOT NULL,
    email         TEXT        NOT NULL,
    password_hash TEXT        NOT NULL,
    full_name     TEXT,
    role          TEXT        NOT NULL DEFAULT 'User',
    is_active     BOOLEAN     NOT NULL DEFAULT TRUE,
    created_at    TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at    TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE UNIQUE INDEX IF NOT EXISTS uq_users_username ON users (username);
CREATE UNIQUE INDEX IF NOT EXISTS uq_users_email    ON users (email);

-- -----------------------------------------------------------------------------
-- requirements  — product requirements
-- -----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS requirements (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title       TEXT        NOT NULL,
    description TEXT,
    status      TEXT        NOT NULL DEFAULT 'draft',      -- draft | approved | in_progress | done | cancelled
    priority    TEXT        NOT NULL DEFAULT 'medium',     -- low | medium | high | critical
    created_by  BIGINT      NOT NULL REFERENCES users (id),
    created_at  TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at  TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_requirements_created_by ON requirements (created_by);
CREATE INDEX IF NOT EXISTS idx_requirements_status     ON requirements (status);

-- -----------------------------------------------------------------------------
-- applications  — frontend apps, backend services, etc.
-- -----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS applications (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name        TEXT        NOT NULL,
    description TEXT,
    app_type    TEXT,                                       -- frontend | backend | service | other
    status      TEXT        NOT NULL DEFAULT 'active',      -- active | inactive | archived
    owner_id    BIGINT      REFERENCES users (id),          -- responsible developer
    created_at  TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at  TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_applications_owner_id ON applications (owner_id);
CREATE UNIQUE INDEX IF NOT EXISTS uq_applications_name  ON applications (name);

-- -----------------------------------------------------------------------------
-- requirement_applications  — traceability between requirements and applications
-- -----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS requirement_applications (
    requirement_id  BIGINT NOT NULL REFERENCES requirements (id) ON DELETE CASCADE,
    application_id  BIGINT NOT NULL REFERENCES applications (id) ON DELETE CASCADE,
    trace_type      TEXT   NOT NULL DEFAULT 'implements',     -- implements | depends_on
    created_at      TIMESTAMPTZ NOT NULL DEFAULT now(),
    PRIMARY KEY (requirement_id, application_id, trace_type),
    FOREIGN KEY (requirement_id) REFERENCES requirements (id) ON DELETE CASCADE,
    FOREIGN KEY (application_id) REFERENCES applications (id) ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS idx_req_app_application ON requirement_applications (application_id);